### ISSUE TITLE
Minimum rust version not correct for bam.

### ISSUE THREAD

**Issue by TyberiusPrime** [zaeleus/noodles#315]
Using rust 1.80.0, I received the following errors;
```
    Checking noodles-bam v0.72.0
error[E0658]: use of unstable library feature 'iter_repeat_n'
  --> /home/f/.cargo/registry/src/index.crates.io-6f17d22bba15001f/noodles-bam-0.72.0/src/record/codec/encoder/quality_scores.rs:28:20
   |
28 |         dst.extend(iter::repeat_n(MISSING, base_count));
   |                    ^^^^^^^^^^^^^^
   |
   = note: see issue #104434 <https://github.com/rust-lang/rust/issues/104434> for more information

error[E0658]: referencing statics in constants is unstable
  --> /home/f/.cargo/registry/src/index.crates.io-6f17d22bba15001f/noodles-bam-0.72.0/src/io/reader/header.rs:25:56
   |
25 |     fn read_magic_number(&mut self) -> io::Result<[u8; MAGIC_NUMBER.len()]> {
   |                                                        ^^^^^^^^^^^^
   |
   = note: see issue #119618 <https://github.com/rust-lang/rust/issues/119618> for more information
   = note: `static` and `const` variables can refer to other `const` variables. A `const` variable, however, cannot refer to a `static` variable.
   = help: to fix this, the value can be extracted to a `const` and then used.
```

They went away when I upgraded to 1.83.0.

I believe the declared minimum rust version is 1.70.0?
At least that's what's in the workspaces' cargo.toml, and the bam crate referes to that.

I suppose the magic number could be a constant though.

**Comment by zaeleus** [comment]
Thanks for reporting.

I backported [`std::iter::repeat_n`](https://doc.rust-lang.org/std/iter/fn.repeat_n.html) (stabilized in Rust 1.82.0) and changed the references to statics in `const` contexts (1.83.0). One direct dependency bstr 1.11.3 requires Rust 1.73.0; and one indirect dependency yoke 0.7.5, 1.71.1. Therefore, I raised the MSRV of noodles to 1.73.0 in 87808faf9a56bb603c50bcebf3603b7741a5b8d8.
