### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by PoisonAlien** [zaeleus/noodles#1]
Hi,
I am trying to use this library as a replacement to `rust-htslib`. I am getting compilation error while trying to run examples. This can be reproduced both on macOS and centOS.

```rust
> git clone https://github.com/zaeleus/noodles
> cd noodles/
> cargo run --release --example bam_write > sample.bam
    Updating crates.io index
  Downloaded byteorder v1.3.4
  Downloaded bit-vec v0.6.2
  Downloaded indexmap v1.5.0
  Downloaded flate2 v1.0.16
  Downloaded hashbrown v0.8.1
  Downloaded miniz_oxide v0.4.0
  Downloaded cfg-if v0.1.10
  Downloaded adler v0.2.3
  Downloaded libc v0.2.73
  Downloaded crc32fast v1.2.0
   Compiling autocfg v1.0.0
   Compiling crc32fast v1.2.0
   Compiling libc v0.2.73
   Compiling cfg-if v0.1.10
   Compiling byteorder v1.3.4
   Compiling adler v0.2.3
   Compiling bitflags v1.2.1
   Compiling bit-vec v0.6.2
   Compiling miniz_oxide v0.4.0
   Compiling hashbrown v0.8.1
   Compiling indexmap v1.5.0
   Compiling flate2 v1.0.16
   Compiling noodles-bgzf v0.1.0 (/home/mayakond/noodles/noodles-bgzf)
error[E0599]: no associated item named `MAX` found for type `u16` in the current scope
 --> noodles-bgzf/src/virtual_position.rs:6:56
  |
6 | pub(crate) const MAX_UNCOMPRESSED_POSITION: u16 = u16::MAX; // 2^16 - 1;
  |                                                        ^^^ associated item not found in `u16`
  |
help: you are looking for the module in `std`, not the primitive type
  |
6 | pub(crate) const MAX_UNCOMPRESSED_POSITION: u16 = std::u16::MAX; // 2^16 - 1;
  |                                                   ^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `noodles-bgzf`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by zaeleus** [comment]
Hi @PoisonAlien! Thanks for submitting an issue.

I track the latest stable version of Rust because noodles currently doesn't enforce a minimum supported Rust version (MSRV). The compilation error you're getting comes from using an old(er) version of Rust. Numeric primitives gained associated constants in Rust 1.43.0: <https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html#library-changes>.

Can you update Rust to at least 1.43.0, e.g., via `rustup update`, and try again?

**Comment by PoisonAlien** [comment]
Indeed that was the case! It works on 1.43.0
Thanks for the quick response.
