### ISSUE TITLE
Trait bounds changes in noodles_sam 0.62.0

### ISSUE THREAD

**Issue by mbhall88** [zaeleus/noodles#282]
I noticed something unexpected in my codebase when I update `noodles_sam` from 0.61.0 to 0.62.0

An mentioned in https://github.com/zaeleus/noodles/discussions/256#discussioncomment-10078479, I had implement a trait on the `Record` trait and this was all working fine. But now, when I try to compile I get the following error

```
$ cargo build
   Compiling sparsley v0.1.0 (/Users/michael/Projects/sparsley)
error[E0599]: the method `mismatches` exists for struct `Box<dyn Record>`, but its trait bounds were not satisfied
   --> src/main.rs:42:34
    |
42  |           let _mismatches = record.mismatches(None).context("Failed to get mismatches")?;
    |                                    ^^^^^^^^^^ method cannot be called on `Box<dyn Record>` due to unsatisfied trait bounds
    |
   ::: /Users/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/noodles-sam-0.61.0/src/alignment/record.rs:29:1
    |
29  |   pub trait Record {
    |   ---------------- doesn't satisfy `_: Mismatches`, `_: Record` or `dyn noodles_sam::alignment::record::Record: Sized`
    |
   ::: /Users/michael/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:196:1
    |
196 | / pub struct Box<
197 | |     T: ?Sized,
198 | |     #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global,
199 | | >(Unique<T>, A);
    | |_- doesn't satisfy `_: Mismatches` or `_: Record`
    |
    = note: the following trait bounds were not satisfied:
            `Box<dyn noodles_sam::alignment::record::Record>: noodles_sam::alignment::record::Record`
            which is required by `Box<dyn noodles_sam::alignment::record::Record>: Mismatches`
            `dyn noodles_sam::alignment::record::Record: Sized`
            which is required by `dyn noodles_sam::alignment::record::Record: Mismatches`
            `dyn noodles_sam::alignment::record::Record: noodles_sam::alignment::record::Record`
            which is required by `dyn noodles_sam::alignment::record::Record: Mismatches`

warning: unused import: `Mismatches`
 --> src/main.rs:7:21
  |
7 | use sparsley::{cli, Mismatches};
  |                     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

For reference, my trait looks something like this

`lib.rs`

```rust
use noodles_fasta::Record as FastaRecord;
use noodles_sam::alignment::Record;

#[derive(Debug, Default, PartialEq)]
pub struct Mismatch {
    pub pos: usize,
    pub alt: u8,
}

pub trait Mismatches {
    fn mismatches(&self, reference: Option<&FastaRecord>) -> Result<Vec<Mismatch>>;
}

impl<T> Mismatches for T
where
    T: Record,
{
    /// Returns a list of mismatches between the read and the reference sequence.
    /// If a reference sequence is provided, the mismatches are calculated based on the CIGAR string.
    /// If no reference sequence is provided, the mismatches are calculated based on the MD tag.
    /// If no MD tag is present, and no reference sequence is provided, an error is returned.
    fn mismatches(&self, reference: Option<&FastaRecord>) -> Result<Vec<Mismatch>> {
        let md_tag = self.md_tag();
        // implementation
}
```

use in `main.rs`

```rust
use sparsley::Mismatches;
use noodles_util::alignment::io::reader::Builder;

fn main() -> Result<()> {
    let mut reader =  Builder::default()
            .build_from_reader(std::io::stdin())
            .context("Failed to read alignment from stdin")?;

    let header = reader.read_header().context("Failed to read header")?;
    for result in reader.records(&header) {
        let record = result.context("Failed to read record")?;
        let _astart = record.alignment_start().unwrap().unwrap();
        let _aspan = record.alignment_span().unwrap().unwrap();
        let _mismatches = record.mismatches(None).context("Failed to get mismatches")?;

    }
}
```

**Comment by mbhall88** [comment]
urgh nevermind, I also had to update `noodles_util` from 0.48.0 to 0.49.0, then this error went away
